#!/usr/bin/env bash
# Generates README.md from the current state of data/.
# Discovers all project memory directories and global config files,
# then writes a navigable index with relative links.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DATA_DIR="$REPO_DIR/data/claude"
README="$REPO_DIR/README.md"

# Exit cleanly if no data has been synced yet
if [ ! -d "$DATA_DIR" ]; then
  echo "No data directory found. Skipping README generation."
  exit 0
fi

# --- Discover projects ---
PROJECTS_DIR="$DATA_DIR/projects"

work_rows=""
personal_rows=""
work_count=0
personal_count=0

if [ -d "$PROJECTS_DIR" ]; then
  for proj_dir in "$PROJECTS_DIR"/*/; do
    [ ! -d "$proj_dir/memory" ] && continue
    [ ! -f "$proj_dir/memory/MEMORY.md" ] && continue

    encoded_name=$(basename "$proj_dir")
    rel_memory="data/claude/projects/$encoded_name/memory/MEMORY.md"

    # Extract readable project name from encoded path
    # Strip the -Users-<username>- prefix (username may contain hyphens)
    # by finding the first known directory marker (code, Projects, etc.)
    proj_name=$(echo "$encoded_name" | sed -E 's/^-Users-.*-(code|Projects)/\1/' | awk -F'-' '{
      for (i=1; i<=NF; i++) {
        if ($i == "code" || $i == "Projects") {
          rest = ""
          for (j=i+1; j<=NF; j++) {
            rest = (rest == "" ? $j : rest "-" $j)
          }
          if (rest != "") { print rest; exit }
        }
      }
      print $0
    }')
    [ -z "$proj_name" ] && proj_name="$encoded_name"
    # The bare ~/code project (global context) has no sub-project name
    [ "$proj_name" = "code" ] && proj_name="~/code (global)"

    # Find extra memory files
    extras=""
    for f in "$proj_dir"/memory/*.md; do
      [ ! -f "$f" ] && continue
      fname=$(basename "$f")
      [ "$fname" = "MEMORY.md" ] && continue
      rel_extra="data/claude/projects/$encoded_name/memory/$fname"
      label=$(echo "$fname" | sed 's/\.md$//' | tr '_-' '  ')
      if [ -z "$extras" ]; then
        extras="[$label]($rel_extra)"
      else
        extras="$extras, [$label]($rel_extra)"
      fi
    done
    [ -z "$extras" ] && extras="-"

    row="| $proj_name | [memory]($rel_memory) | $extras |"

    if echo "$encoded_name" | grep -qE "\-code(\-|$)"; then
      work_rows="${work_rows:+$work_rows
}$row"
      work_count=$((work_count + 1))
    else
      personal_rows="${personal_rows:+$personal_rows
}$row"
      personal_count=$((personal_count + 1))
    fi
  done
fi

# --- Discover global config files ---
config_rows=""
for f in CLAUDE.md settings.json config.json remote-settings.json package.json; do
  if [ -f "$DATA_DIR/$f" ]; then
    row="| $f | [data/claude/$f](data/claude/$f) |"
    config_rows="${config_rows:+$config_rows
}$row"
  fi
done

# --- Discover agents, commands, hooks, skills ---
extras_lines=""
for dir_name in agents commands hooks skills; do
  dir_path="$DATA_DIR/$dir_name"
  [ ! -d "$dir_path" ] && continue
  count=$(find "$dir_path" -type f | wc -l | tr -d ' ')
  [ "$count" -eq 0 ] && continue
  line="- [\`$dir_name/\`](data/claude/$dir_name/) ($count files)"
  extras_lines="${extras_lines:+$extras_lines
}$line"
done

# --- Write README ---
{
  cat <<'HEADER'
# AI Knowledge Base

Private backup of AI assistant memories, project context, and configuration.
Synced daily via [AiSyncing](https://github.com/DiegoSalazar/AiSyncing).
This README is auto-generated from backed up data on each push.

HEADER

  if [ $work_count -gt 0 ]; then
    echo "## Work Projects"
    echo ""
    echo "| Project | Memory | Extra |"
    echo "|---------|--------|-------|"
    echo "$work_rows"
    echo ""
  fi

  if [ $personal_count -gt 0 ]; then
    echo "## Personal Projects"
    echo ""
    echo "| Project | Memory | Extra |"
    echo "|---------|--------|-------|"
    echo "$personal_rows"
    echo ""
  fi

  if [ -n "$config_rows" ]; then
    echo "## Global Config"
    echo ""
    echo "| File | Path |"
    echo "|------|------|"
    echo "$config_rows"
    echo ""
  fi

  if [ -n "$extras_lines" ]; then
    echo "## Additional Resources"
    echo "$extras_lines"
    echo ""
  fi

  echo "---"
  echo ""
  echo "*Auto-generated by [generate-readme.sh](scripts/generate-readme.sh).*"

} > "$README"

echo "README.md generated with $work_count work and $personal_count personal projects."
